// Copyright 2024 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

/**
 * Reason for transaction failure.
 */
export enum TransactionFailureReason {
    None = 0,
    TypeInvalid = 1,
    Conflicting = 2,
    InputAlreadySpent = 3,
    InputCreationAfterTxCreation = 4,
    UnlockSignatureInvalid = 5,
    CommitmentInputMissing = 6,
    CommitmentInputReferenceInvalid = 7,
    BicInputReferenceInvalid = 8,
    RewardInputReferenceInvalid = 9,
    StakingRewardCalculationFailure = 10,
    DelegationRewardCalculationFailure = 11,
    InputOutputBaseTokenMismatch = 12,
    ManaOverflow = 13,
    InputOutputManaMismatch = 14,
    ManaDecayCreationIndexExceedsTargetIndex = 15,
    NativeTokenAmountLessThanZero = 16,
    NativeTokenSumExceedsUint256 = 17,
    NativeTokenSumUnbalanced = 18,
    MultiAddressLengthUnlockLengthMismatch = 19,
    MultiAddressUnlockThresholdNotReached = 20,
    NestedMultiUnlock = 21,
    SenderFeatureNotUnlocked = 22,
    IssuerFeatureNotUnlocked = 23,
    StakingRewardInputMissing = 24,
    StakingBlockIssuerFeatureMissing = 25,
    StakingCommitmentInputMissing = 26,
    StakingRewardClaimingInvalid = 27,
    StakingFeatureRemovedBeforeUnbonding = 28,
    StakingFeatureModifiedBeforeUnbonding = 29,
    StakingStartEpochInvalid = 30,
    StakingEndEpochTooEarly = 31,
    BlockIssuerCommitmentInputMissing = 32,
    BlockIssuanceCreditInputMissing = 33,
    BlockIssuerNotExpired = 34,
    BlockIssuerExpiryTooEarly = 35,
    ManaMovedOffBlockIssuerAccount = 36,
    AccountLocked = 37,
    TimelockCommitmentInputMissing = 38,
    TimelockNotExpired = 39,
    ExpirationCommitmentInputMissing = 40,
    ExpirationNotUnlockable = 41,
    ReturnAmountNotFulFilled = 42,
    NewChainOutputHasNonZeroedId = 43,
    ChainOutputImmutableFeaturesChanged = 44,
    ImplicitAccountDestructionDisallowed = 45,
    MultipleImplicitAccountCreationAddresses = 46,
    AccountInvalidFoundryCounter = 47,
    FoundryTransitionWithoutAccount = 48,
    FoundrySerialInvalid = 49,
    DelegationCommitmentInputMissing = 50,
    DelegationRewardInputMissing = 51,
    DelegationRewardsClaimingInvalid = 52,
    DelegationOutputTransitionedTwice = 53,
    DelegationModified = 54,
    DelegationStartEpochInvalid = 55,
    DelegationAmountMismatch = 56,
    DelegationEndEpochNotZero = 57,
    DelegationEndEpochInvalid = 58,
    CapabilitiesNativeTokenBurningNotAllowed = 59,
    CapabilitiesManaBurningNotAllowed = 60,
    CapabilitiesAccountDestructionNotAllowed = 61,
    CapabilitiesAnchorDestructionNotAllowed = 62,
    CapabilitiesFoundryDestructionNotAllowed = 63,
    CapabilitiesNftDestructionNotAllowed = 64,
    SemanticValidationFailed = 255,
}

/**
 * Transaction failure reason strings.
 */
export const TRANSACTION_FAILURE_REASON_STRINGS: {
    [key in TransactionFailureReason]: string;
} = {
    [TransactionFailureReason.None]: '',
    [TransactionFailureReason.TypeInvalid]: '',
    [TransactionFailureReason.Conflicting]: '',
    [TransactionFailureReason.InputAlreadySpent]: '',
    [TransactionFailureReason.InputCreationAfterTxCreation]: '',
    [TransactionFailureReason.UnlockSignatureInvalid]: '',
    [TransactionFailureReason.CommitmentInputMissing]: '',
    [TransactionFailureReason.CommitmentInputReferenceInvalid]: '',
    [TransactionFailureReason.BicInputReferenceInvalid]: '',
    [TransactionFailureReason.RewardInputReferenceInvalid]: '',
    [TransactionFailureReason.StakingRewardCalculationFailure]: '',
    [TransactionFailureReason.DelegationRewardCalculationFailure]: '',
    [TransactionFailureReason.InputOutputBaseTokenMismatch]: '',
    [TransactionFailureReason.ManaOverflow]: '',
    [TransactionFailureReason.InputOutputManaMismatch]: '',
    [TransactionFailureReason.ManaDecayCreationIndexExceedsTargetIndex]: '',
    [TransactionFailureReason.NativeTokenAmountLessThanZero]: '',
    [TransactionFailureReason.NativeTokenSumExceedsUint256]: '',
    [TransactionFailureReason.NativeTokenSumUnbalanced]: '',
    [TransactionFailureReason.MultiAddressLengthUnlockLengthMismatch]: '',
    [TransactionFailureReason.MultiAddressUnlockThresholdNotReached]: '',
    [TransactionFailureReason.NestedMultiUnlock]: '',
    [TransactionFailureReason.SenderFeatureNotUnlocked]: '',
    [TransactionFailureReason.IssuerFeatureNotUnlocked]: '',
    [TransactionFailureReason.StakingRewardInputMissing]: '',
    [TransactionFailureReason.StakingBlockIssuerFeatureMissing]: '',
    [TransactionFailureReason.StakingCommitmentInputMissing]: '',
    [TransactionFailureReason.StakingRewardClaimingInvalid]: '',
    [TransactionFailureReason.StakingFeatureRemovedBeforeUnbonding]: '',
    [TransactionFailureReason.StakingFeatureModifiedBeforeUnbonding]: '',
    [TransactionFailureReason.StakingStartEpochInvalid]: '',
    [TransactionFailureReason.StakingEndEpochTooEarly]: '',
    [TransactionFailureReason.BlockIssuerCommitmentInputMissing]: '',
    [TransactionFailureReason.BlockIssuanceCreditInputMissing]: '',
    [TransactionFailureReason.BlockIssuerNotExpired]: '',
    [TransactionFailureReason.BlockIssuerExpiryTooEarly]: '',
    [TransactionFailureReason.ManaMovedOffBlockIssuerAccount]: '',
    [TransactionFailureReason.AccountLocked]: '',
    [TransactionFailureReason.TimelockCommitmentInputMissing]: '',
    [TransactionFailureReason.TimelockNotExpired]: '',
    [TransactionFailureReason.ExpirationCommitmentInputMissing]: '',
    [TransactionFailureReason.ExpirationNotUnlockable]: '',
    [TransactionFailureReason.ReturnAmountNotFulFilled]: '',
    [TransactionFailureReason.NewChainOutputHasNonZeroedId]: '',
    [TransactionFailureReason.ChainOutputImmutableFeaturesChanged]: '',
    [TransactionFailureReason.ImplicitAccountDestructionDisallowed]: '',
    [TransactionFailureReason.MultipleImplicitAccountCreationAddresses]: '',
    [TransactionFailureReason.AccountInvalidFoundryCounter]: '',
    [TransactionFailureReason.FoundryTransitionWithoutAccount]: '',
    [TransactionFailureReason.FoundrySerialInvalid]: '',
    [TransactionFailureReason.DelegationCommitmentInputMissing]: '',
    [TransactionFailureReason.DelegationRewardInputMissing]: '',
    [TransactionFailureReason.DelegationRewardsClaimingInvalid]: '',
    [TransactionFailureReason.DelegationOutputTransitionedTwice]: '',
    [TransactionFailureReason.DelegationModified]: '',
    [TransactionFailureReason.DelegationStartEpochInvalid]: '',
    [TransactionFailureReason.DelegationAmountMismatch]: '',
    [TransactionFailureReason.DelegationEndEpochNotZero]: '',
    [TransactionFailureReason.DelegationEndEpochInvalid]: '',
    [TransactionFailureReason.CapabilitiesNativeTokenBurningNotAllowed]: '',
    [TransactionFailureReason.CapabilitiesManaBurningNotAllowed]: '',
    [TransactionFailureReason.CapabilitiesAccountDestructionNotAllowed]: '',
    [TransactionFailureReason.CapabilitiesAnchorDestructionNotAllowed]: '',
    [TransactionFailureReason.CapabilitiesFoundryDestructionNotAllowed]: '',
    [TransactionFailureReason.CapabilitiesNftDestructionNotAllowed]: '',
    [TransactionFailureReason.SemanticValidationFailed]: '',
};
