/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "plugins": [
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "iota-sdk",
        "path": "/Users/ani/Documents/iota/iotaledger/iota-sdk/documentation/sdk/docs",
        "routeBasePath": "iota-sdk",
        "sidebarPath": "/Users/ani/Documents/iota/iotaledger/iota-sdk/documentation/sdk/sidebars.js",
        "editUrl": "https://github.com/iotaledger/iota-sdk/edit/documentation/sdk",
        "remarkPlugins": [
          null,
          null
        ]
      }
    ],
    "plugin-image-zoom"
  ],
  "staticDirectories": [
    "/Users/ani/Documents/iota/iotaledger/iota-sdk/documentation/sdk/static",
    "/Users/ani/Documents/iota/iotaledger/iota-sdk/documentation/sdk/node_modules/@iota-wiki/cli/dist/cli/src/docusaurus/static"
  ],
  "title": "IOTA Wiki",
  "tagline": "The complete reference for IOTA",
  "url": "https://wiki.iota.org",
  "baseUrl": "/",
  "favicon": "img/favicon.ico",
  "trailingSlash": true,
  "organizationName": "iota-wiki",
  "projectName": "iota-wiki",
  "stylesheets": [
    "https://fonts.googleapis.com/css?family=Material+Icons",
    {
      "href": "https://cdn.jsdelivr.net/npm/katex@0.13.24/dist/katex.min.css",
      "type": "text/css",
      "integrity": "sha384-odtC+0UGzzFL/6PNoE8rX/SPcQDXBJ+uRepguP4QkPCm2LBxH3FA3y+fKSiJ+AmM",
      "crossorigin": "anonymous"
    }
  ],
  "themes": [
    [
      "@docusaurus/theme-classic",
      {
        "customCss": "/Users/ani/Documents/iota/iotaledger/iota-sdk/documentation/sdk/node_modules/@iota-wiki/cli/dist/src/next/css/custom.css"
      }
    ],
    "/Users/ani/Documents/iota/iotaledger/iota-sdk/documentation/sdk/node_modules/@iota-wiki/cli/dist/cli/src/docusaurus/theme"
  ],
  "themeConfig": {
    "image": "img/shimmer-wiki.png",
    "imageZoom": {
      "selector": ".markdown :not(a) > img:not(.image-gallery-image):not(.image-gallery-thumbnail-image)",
      "options": {
        "background": "rgba(0, 0, 0, 0.6)"
      }
    },
    "navbar": {
      "hideOnScroll": true,
      "logo": {
        "alt": "IOTA Wiki Logo",
        "src": "img/logo_next.svg",
        "srcDark": "img/logo_next_dark.svg"
      },
      "items": []
    },
    "announcementBar": {
      "id": "preview",
      "content": "This is a local preview. Please find available routes <a href=\"/404\">here</a>.",
      "isCloseable": false
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "prism": {
      "additionalLanguages": [],
      "theme": {
        "plain": {
          "color": "#bfc7d5",
          "backgroundColor": "#292d3e"
        },
        "styles": [
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(105, 112, 152)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "string",
              "inserted"
            ],
            "style": {
              "color": "rgb(195, 232, 141)"
            }
          },
          {
            "types": [
              "number"
            ],
            "style": {
              "color": "rgb(247, 140, 108)"
            }
          },
          {
            "types": [
              "builtin",
              "char",
              "constant",
              "function"
            ],
            "style": {
              "color": "rgb(130, 170, 255)"
            }
          },
          {
            "types": [
              "punctuation",
              "selector"
            ],
            "style": {
              "color": "rgb(199, 146, 234)"
            }
          },
          {
            "types": [
              "variable"
            ],
            "style": {
              "color": "rgb(191, 199, 213)"
            }
          },
          {
            "types": [
              "class-name",
              "attr-name"
            ],
            "style": {
              "color": "rgb(255, 203, 107)"
            }
          },
          {
            "types": [
              "tag",
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 114)"
            }
          },
          {
            "types": [
              "operator"
            ],
            "style": {
              "color": "rgb(137, 221, 255)"
            }
          },
          {
            "types": [
              "boolean"
            ],
            "style": {
              "color": "rgb(255, 88, 116)"
            }
          },
          {
            "types": [
              "keyword"
            ],
            "style": {
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "doctype"
            ],
            "style": {
              "color": "rgb(199, 146, 234)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "color": "rgb(178, 204, 214)"
            }
          },
          {
            "types": [
              "url"
            ],
            "style": {
              "color": "rgb(221, 221, 221)"
            }
          }
        ]
      },
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "onBrokenLinks": "log",
  "onBrokenMarkdownLinks": "log",
  "onDuplicateRoutes": "log",
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "customFields": {},
  "presets": [],
  "scripts": [],
  "headTags": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "mermaid": false
  }
};
