name: Swift bindings checks (wallet)
on:
  push:
    branches: [develop, production]
    paths:
      - ".github/actions/**"
      - "**.rs" # Include all rust files
      - "**Cargo.toml" # Include all Cargo.toml files
      - "**Cargo.lock" # Include all Cargo.lock files
      - "!**/examples/**" # Exclude all examples
      - "!**/tests/**" # Exclude all tests
      - "!**/bindings/**" # Exclude all bindings
      - "!cli/**" # Exclude CLI
      - "sdk/src/wallet/bindings/swift/**" # Re-include swift bindings
      - ".github/workflows/bindings/wallet/swift.yml"
  pull_request:
    branches: [develop, production]
    paths:
      - ".github/actions/**"
      - "**.rs" # Include all rust files
      - "**Cargo.toml" # Include all Cargo.toml files
      - "**Cargo.lock" # Include all Cargo.lock files
      - "!**/examples/**" # Exclude all examples
      - "!**/tests/**" # Exclude all tests
      - "!**/bindings/**" # Exclude all bindings
      - "!cli/**" # Exclude CLI
      - "sdk/src/wallet/bindings/swift/**" # Re-include swift bindings
      - ".github/workflows/bindings/wallet/swift.yml"
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout the Source Code
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Build library
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --all-features --release --manifest-path sdk/src/wallet/bindings/swift/Cargo.toml

      - name: Move built library to xcode folder
        run: mv "$GITHUB_WORKSPACE/target/release/libiota_wallet.dylib" "$GITHUB_WORKSPACE/sdk/src/wallet/bindings/swift/xcode/IotaWallet/iota_wallet"

      - name: Select Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Build project
        run: |
          set -o pipefail
          xcodebuild build -scheme IotaWallet -project IotaWallet.xcodeproj -destination 'platform=macOS' | xcpretty
        working-directory: sdk/src/wallet/bindings/swift/xcode/IotaWallet
