[build-system]
requires = ["maturin>=1.0.0b4"]
build-backend = "maturin"

[project]
name = "iota-sdk"
dependencies = ["dacite >= 1.8.1", "pyhumps >= 3.8.0"]

[tool.maturin]
python-packages = ["iota_sdk"]