/**
 * * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
  docs: [
    {
      type: 'doc',
      id: 'welcome',
    },
    {
      type: 'doc',
      id: 'overview',
    },
    {
      type: 'category',
      label: 'How To',
      items: [
        {
          type: "category",
          label: 'Sign And Verify Ed25519',
          items: [
            {
              type: 'autogenerated',
              dirName: 'how_tos/sign_and_verify_ed25519',
            }
          ]
        },
        {
          type: "category",
          label: 'Simple Transaction',
          items: [
            {
              type: 'autogenerated',
              dirName: 'how_tos/simple_transaction'
            }
          ]
        },
        {
          type: "category",
          label: 'Accounts and Addresses',
          items: [
            {
              type: 'autogenerated',
              dirName: 'how_tos/accounts_and_addresses'
            }
          ]
        },
      ]
    },
    {
      type: 'doc',
      id: 'troubleshooting',
    },
    {
      type: 'doc',
      id: 'contribute',
      label: 'Contribute',
    }
  ]
};