[profile.ci]
# Print out output for failing tests as soon as they fail, and also at the end
# of the run (for easy scrollability).
failure-output = "immediate-final"
fail-fast = false
retries = 2
test-threads = "num-cpus"
slow-timeout = { period = "60s", terminate-after = 2 }

[[profile.ci.overrides]]
filter = 'test(/^pow::/)'
slow-timeout = "5m"
