name: "private-tangle-setup"
description: "Setup a private tangle"
runs:
  using: "composite"
  steps:
    - name: Clone private tangle files
      uses: actions/checkout@v3
      with:
        repository: iotaledger/iota-core
        path: iota-core

    - name: Prepare files for start and stop
      shell: bash
      run: |
        echo "docker compose down -v" >> cleanup.sh
        echo "rm *.snapshot" >> cleanup.sh
        chmod +x cleanup.sh

        # remove the last 5 lines and add docker compose with `-d` to run it in the background
        sed -i -n -e :a -e '1,5!{P;N;D;};N;ba' run.sh
        echo "docker compose -f docker-compose.yml up -d" >> run.sh
      working-directory: iota-core/tools/docker-network

    # Copied from https://github.com/iotaledger/iota-core/blob/926bf11b5fb6dc46b25482770e0ccf1e048b97c9/.github/workflows/unit-test.yml#L16-L19
    - uses: actions/setup-go@v4
      with:
        go-version-file: "iota-core/go.mod"
        cache: false

    - name: Setup private tangle
      shell: bash
      # setup-go sets the PATH for the correct version, but sudo uses a different PATH by default
      run: |
        # Start Tangle
        sudo env "PATH=$PATH" ./run.sh
      working-directory: iota-core/tools/docker-network

    - name: Wait for tangle to start
      shell: bash
      run: wget -qO- https://raw.githubusercontent.com/eficode/wait-for/v2.2.4/wait-for | sh -s -- -t 240 http://localhost:8050/health -- echo "Tangle is up"
    - name: Wait for faucet to start
      shell: bash
      run: wget -qO- https://raw.githubusercontent.com/eficode/wait-for/v2.2.4/wait-for | sh -s -- -t 240 http://localhost:8088/health -- echo "Faucet is up"
