name: "private-tangle-setup"
description: "Setup a private tangle"
runs:
  using: "composite"
  steps:
    - name: Clone private tangle files
      uses: actions/checkout@v3
      with:
        repository: iotaledger/iota-core
        path: iota-core

    - name: Prepare files for start and stop
      shell: bash
      run: |
        echo "docker compose down -v" >> cleanup.sh
        echo "rm *.snapshot" >> cleanup.sh
        chmod +x cleanup.sh

        sed -i -n -e :a -e '1,5!{P;N;D;};N;ba' run.sh
        echo "docker compose -f \$DOCKER_COMPOSE_FILE up -d" >> run.sh
      working-directory: iota-core/tools/docker-network

    - name: Setup private tangle
      shell: bash
      run: |
        # Start Tangle
        sudo ./run.sh
      working-directory: iota-core/tools/docker-network

    - name: Wait for tangle to start
      shell: bash
      run: wget -qO- https://raw.githubusercontent.com/eficode/wait-for/v2.2.4/wait-for | sh -s -- -t 120 http://localhost:8080/health -- echo "Tangle is up"
    # TODO enable, maybe need another URL
    # - name: Wait for faucet to start
      # shell: bash
      # run: wget -qO- https://raw.githubusercontent.com/eficode/wait-for/v2.2.4/wait-for | sh -s -- -t 120 http://localhost:8081/api/info -- echo "Faucet is up"
