name: 'private-tangle-tear-down'
description: 'tear-down a private tangle'
runs:
  using: "composite"
  steps:
    - name: Tear down private tangle
      shell: bash
      run: |
        sudo ./cleanup.sh
        # sudo docker compose kill
        # sudo docker compose down
      working-directory: iota-core/tools/docker-network
