name: Nodejs bindings checks (wallet)

on: workflow_call

env:
  CARGO_INCREMENTAL: 0

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        node: ["18"]

    steps:
      - name: Checkout the Source Code
        uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Set Up Node.js ${{ matrix.node }} and Yarn Cache
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
          cache-dependency-path: sdk/src/wallet/bindings/nodejs/yarn.lock

      # This step is required for bindgen to work on Windows.
      - name: Set Up Clang/LLVM (Windows)
        if: ${{ startsWith(matrix.os, 'windows') }}
        uses: ./.github/actions/setup-clang

      - name: Install Required Dependencies (Ubuntu)
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          sudo apt-get update
          sudo apt-get install libudev-dev libusb-1.0-0-dev

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "sdk/src/wallet/bindings/nodejs -> target"

      - name: Run Yarn Install
        working-directory: sdk/src/wallet/bindings/nodejs/
        run: yarn install

      - name: Run Yarn Rebuild
        working-directory: sdk/src/wallet/bindings/nodejs/
        run: yarn rebuild

      - name: Run Yarn Test
        working-directory: sdk/src/wallet/bindings/nodejs/
        run: yarn test

  lint:
    name: Lint
    if: ${{ ! github.event.schedule }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Source Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: sdk/src/wallet/bindings/nodejs/yarn.lock
          node-version: 18.x

      - name: Install Dependencies
        working-directory: sdk/src/wallet/bindings/nodejs/
        run: yarn install --ignore-scripts

      - name: Lint
        working-directory: sdk/src/wallet/bindings/nodejs/
        run: yarn lint

  check-format:
    name: Check Format
    if: ${{ ! github.event.schedule }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Source Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          cache: yarn
          cache-dependency-path: sdk/src/wallet/bindings/nodejs/yarn.lock
          node-version: 18.x

      - name: Install Dependencies
        working-directory: sdk/src/wallet/bindings/nodejs/
        run: yarn install --ignore-scripts

      - name: Format
        working-directory: sdk/src/wallet/bindings/nodejs/
        run: yarn format-check
