name: Bindings

on:
  push:
    branches: [develop, production]
    paths:
      - ".github/actions/**"
      - "**.rs" # Include all rust files
      - "**Cargo.toml" # Include all Cargo.toml files
      - "**Cargo.lock" # Include all Cargo.lock files
      - "!**/examples/**" # Exclude all examples
      - "!**/tests/**" # Exclude all tests
      - "!cli/**" # Exclude CLI
      - "sdk/src/*/bindings/**"
      - ".github/workflows/bindings/**"
  pull_request:
    branches: [develop, production]
    paths:
      - ".github/actions/**"
      - "**.rs" # Include all rust files
      - "**Cargo.toml" # Include all Cargo.toml files
      - "**Cargo.lock" # Include all Cargo.lock files
      - "!**/examples/**" # Exclude all examples
      - "!**/tests/**" # Exclude all tests
      - "!cli/**" # Exclude CLI
      - "sdk/src/*/bindings/**"
      - ".github/workflows/bindings/**"
  schedule:
    - cron: "0 1 * * *"
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  paths-filter:
    runs-on: ubuntu-latest
    outputs:
      filters: ${{ steps.filter.outputs }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            client-covector:
              - "sdk/src/client/bindings/covector/**"
              - ".github/workflows/bindings/client/covector.yml"
            client-java:
              - "sdk/src/client/bindings/java/**"
              - ".github/workflows/bindings/client/java.yml"
            client-nodejs:
              - "sdk/src/client/bindings/nodejs/**"
              - ".github/workflows/bindings/client/nodejs.yml"
            client-python:
              - "sdk/src/client/bindings/python/**"
              - ".github/workflows/bindings/client/python.yml"
            client-wasm:
              - "sdk/src/client/bindings/wasm/**"
              - ".github/workflows/bindings/client/wasm.yml"
            wallet-swift:
              - "sdk/src/wallet/bindings/swift/**"
              - ".github/workflows/bindings/wallet/swift.yml"
            wallet-java:
              - "sdk/src/wallet/bindings/java/**"
              - ".github/workflows/bindings/wallet/java.yml"
            wallet-nodejs:
              - "sdk/src/wallet/bindings/nodejs/**"
              - ".github/workflows/bindings/wallet/nodejs.yml"
            wallet-python:
              - "sdk/src/wallet/bindings/python/**"
              - ".github/workflows/bindings/wallet/python.yml"
            wallet-wasm:
              - "sdk/src/wallet/bindings/wasm/**"
              - ".github/workflows/bindings/wallet/wasm.yml"

  client-covector:
    needs: paths-filter
    if: needs.paths-filter.outputs.filters.client-covector == 'true'
    uses: ./.github/workflows/bindings/client/covector.yml

  client-java:
    needs: paths-filter
    if: needs.paths-filter.outputs.filters.client-java == 'true'
    uses: ./.github/workflows/bindings/client/java.yml

  client-nodejs:
    needs: paths-filter
    if: needs.paths-filter.outputs.filters.client-nodejs == 'true'
    uses: ./.github/workflows/bindings/client/nodejs.yml

  client-python:
    needs: paths-filter
    if: needs.paths-filter.outputs.filters.client-python == 'true'
    uses: ./.github/workflows/bindings/client/python.yml

  client-wasm:
    needs: paths-filter
    if: needs.paths-filter.outputs.filters.client-wasm == 'true'
    uses: ./.github/workflows/bindings/client/wasm.yml

  wallet-swift:
    needs: paths-filter
    if: needs.paths-filter.outputs.filters.wallet-swift == 'true'
    uses: ./.github/workflows/bindings/wallet/swift.yml

  wallet-java:
    needs: paths-filter
    if: needs.paths-filter.outputs.filters.wallet-java == 'true'
    uses: ./.github/workflows/bindings/wallet/java.yml

  wallet-nodejs:
    needs: paths-filter
    if: needs.paths-filter.outputs.filters.wallet-nodejs == 'true'
    uses: ./.github/workflows/bindings/wallet/nodejs.yml

  wallet-python:
    needs: paths-filter
    if: needs.paths-filter.outputs.filters.wallet-python == 'true'
    uses: ./.github/workflows/bindings/wallet/python.yml

  wallet-wasm:
    needs: paths-filter
    if: needs.paths-filter.outputs.filters.wallet-wasm == 'true'
    uses: ./.github/workflows/bindings/wallet/wasm.yml
