name: Java bindings checks (wallet)

on: workflow_call

env:
  CARGO_INCREMENTAL: 0

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        java: ["11", "17"]

    steps:
      - name: Checkout the Source Code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # This step is required for bindgen to work on Windows.
      - name: Set Up Clang/LLVM (Windows)
        if: ${{ startsWith(matrix.os, 'windows') }}
        uses: ./.github/actions/setup-clang

      - name: Install Required Dependencies (Ubuntu)
        if: ${{ startsWith(matrix.os, 'ubuntu') }}
        run: |
          sudo apt-get update
          sudo apt-get install libudev-dev libusb-1.0-0-dev

      - name: Set Up Java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: "temurin"

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2
        with:
          cache-directories: "sdk/src/wallet/bindings/java/lib/native/"

      - name: Run Gradle Test
        shell: bash
        working-directory: sdk/src/wallet/bindings/java/
        run: |
          chmod +x gradlew
          ./gradlew test -i
