name: Build and Run Tests

on:
  push:
    branches: [develop, staging, "2.0"]
    paths:
      - ".cargo/config.toml"
      - ".github/workflows/build-and-test.yml"
      - ".github/actions/**"
      - "**.rs" # Include all rust files
      - "**Cargo.toml" # Include all Cargo.toml files
      - "**Cargo.lock" # Include all Cargo.lock files
      - "!**/bindings/**" # Exclude all bindings
  pull_request:
    branches: [develop, staging, "2.0"]
    paths:
      - ".cargo/config.toml"
      - ".github/workflows/build-and-test.yml"
      - ".github/actions/**"
      - "**.rs" # Include all rust files
      - "**Cargo.toml" # Include all Cargo.toml files
      - "**Cargo.lock" # Include all Cargo.lock files
      - "!**/bindings/**" # Exclude all bindings

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  crate:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        # os: [windows-latest, macos-latest, ubuntu-latest]
        os: [windows-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Rust
        uses: ./.github/actions/setup-rust

      # Required for ledger-nano
      - name: Install required packages (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libudev-dev libusb-1.0-0-dev

      - name: Install Nextest
        uses: taiki-e/install-action@nextest

      - name: Run tests
        run: cargo ci-test
