name: Build and Run Tests

on:
  push:
    branches: [develop, production]
    paths:
      - ".github/workflows/core.yml"
      - ".github/actions/**"
      - "**.rs" # Include all rust files
      - "**Cargo.toml" # Include all Cargo.toml files
      - "**Cargo.lock" # Include all Cargo.lock files
      - "!**/bindings/**" # Exclude all bindings
  pull_request:
    branches: [develop, production]
    paths:
      - ".github/workflows/core.yml"
      - ".github/actions/**"
      - "**.rs" # Include all rust files
      - "**Cargo.toml" # Include all Cargo.toml files
      - "**Cargo.lock" # Include all Cargo.lock files
      - "!**/bindings/**" # Exclude all bindings

jobs:
  crate:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # Required for ledger-nano
      - name: Install required packages (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install libudev-dev libusb-1.0-0-dev

      - name: Install Nextest
        uses: taiki-e/install-action@nextest

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run --all-features --no-fail-fast --hide-progress-bar --cargo-profile ci
