name: Common Feature Sets
on:
  push:
    branches: [develop, production, "1.1"]
    paths:
      - ".cargo/config.toml"
      - ".github/workflows/common-features.yml"
      - ".github/actions/**"
      - "**.rs" # Include all rust files
      - "**Cargo.toml" # Include all Cargo.toml files
      - "**Cargo.lock" # Include all Cargo.lock files
      - "!**/bindings/**" # Exclude all bindings
  pull_request:
    branches: [develop, production, "1.1"]
    paths:
      - ".cargo/config.toml"
      - ".github/workflows/common-features.yml"
      - ".github/actions/**"
      - "**.rs" # Include all rust files
      - "**Cargo.toml" # Include all Cargo.toml files
      - "**Cargo.lock" # Include all Cargo.lock files
      - "!**/bindings/**" # Exclude all bindings

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_INCREMENTAL: 0

jobs:
  common-sets:
    name: Check common feature sets
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        set:
          - pow
          - irc_27
          - irc_30
          - client,private_key_secret_manager
          - client,mqtt
          - client,participation
          - wallet,storage
          - wallet,stronghold
          - wallet,rocksdb
          - wallet,participation
          - wallet,events
          - wallet,events,ledger_nano

    steps:
      - name: Checkout the Source Code
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: ./.github/actions/setup-rust

      - name: Check wallet + stronghold
        run: cargo check --no-default-features -p iota-sdk -F ${{ matrix.set }}
