name: Test Docs Build

on:
  pull_request:
    branches: [develop, production, 2.0]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test CLI Build
        run: |
          cd documentation/cli
          yarn install --immutable
          yarn build
      - name: Test SDK Build
        run: |
          cd documentation/sdk
          yarn install --immutable
          yarn build
