name: Test Docs Build

on:
  pull_request:
    branches: [develop, production]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test Build
        run: |
          cd documentation
          yarn install --immutable
          yarn build
