name: Wasm compatibility

on:
  push:
    branches: [develop, production]
    paths:
      - ".github/workflows/wasm-compatibility.yml"
      - ".github/actions/**"
      - "**.rs" # Include all rust files
      - "**Cargo.toml" # Include all Cargo.toml files
      - "**Cargo.lock" # Include all Cargo.lock files
      - "!**/bindings/**" # Exclude all bindings
      - "!cli/**" # Exclude CLI
  pull_request:
    branches: [develop, production]
    paths:
      - ".github/workflows/wasm-compatibility.yml"
      - ".github/actions/**"
      - "**.rs" # Include all rust files
      - "**Cargo.toml" # Include all Cargo.toml files
      - "**Cargo.lock" # Include all Cargo.lock files
      - "!**/bindings/**" # Exclude all bindings
      - "!cli/**" # Exclude CLI

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install stable rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true

      - name: Cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --release --target=wasm32-unknown-unknown --manifest-path sdk/Cargo.toml --no-default-features --features client,tls,events,storage,message_interface,participation,wallet
