// Copyright 2022 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

use crate::{
    client::api::input_selection::Burn,
    // types::block::output::Output,
    wallet::{
        account::{types::Transaction, TransactionOptions},
        Account,
    },
};

pub(crate) mod decrease_native_token_supply;

impl Account {
    /// A generic `burn()` function that can be used to burn native tokens, nfts, foundries and aliases.
    ///
    /// Note that burning **native tokens** doesn't require the foundry output which minted them, but will not increase
    /// the foundries `melted_tokens` field, which makes it impossible to destroy the foundry output. Therefore it's
    /// recommended to use melting, if the foundry output is available.
    pub async fn burn(
        &self,
        burn: impl Into<Burn> + Send,
        options: impl Into<Option<TransactionOptions>> + Send,
    ) -> crate::wallet::Result<Transaction> {
        let burn: Burn = burn.into();
        let mut options: TransactionOptions = options.into().unwrap_or_default();
        options.burn = Some(burn.clone());

        // The empty list of outputs is used. Outputs will be generated by
        // the input selection algorithm based on the content of the [`Burn`] object.
        self.send(vec![], Some(options)).await
    }
}
